'use strict';
// Code-drawn pictures for the Grades 1–5 lesson page (primary.js). Every picture here is SVG built
// from the lesson's own words and numbers: a clock drawn at the lesson's time, the letters the
// lesson blends, the story's own scenes. Nothing is generated by an image model, so a lesson costs
// nothing to draw and a picture can never show a time or a word the lesson does not say.
//
// The pictures are flat and bright, for young children, in the approved design's colours.
const C = {
  navy: '#303749', green: '#298157', mint: '#DEF4E7', teal: '#0F6A73', blue: '#2E5E90', amber: '#F2A20C',
  cream: '#FFF8E8', purple: '#584A93', slate: '#5B6472', ink: '#1F2433', sky: '#D9EEFB', grass: '#8CCB6E',
  leaf: '#4FA35B', trunk: '#8A5A3B', sun: '#FFC93C', pink: '#F48FB1', red: '#E5534B', white: '#FFFFFF',
};
// one colour per letter tile, in turn
const TILE = ['#E5534B', '#2E86DE', '#F2A20C', '#27AE60', '#8E44AD', '#16A085'];

const esc = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const svg = (w, h, body, label) => `<svg class="qart" viewBox="0 0 ${w} ${h}" role="img"${label ? ` aria-label="${esc(label)}"` : ''} xmlns="http://www.w3.org/2000/svg">${body}</svg>`;
const FONT = "font-family=\"Inter,'Noto Nastaliq Urdu',sans-serif\"";

// "9:00" → {h:9, m:0}
function parseTime(t) {
  const m = /^\s*(\d{1,2})\s*[:.]\s*(\d{2})\s*$/.exec(String(t || ''));
  if (!m) throw new Error(`clock: cannot read the time "${t}"`);
  const h = Number(m[1]); const min = Number(m[2]);
  if (h < 0 || h > 23 || min > 59) throw new Error(`clock: "${t}" is not a time`);
  return { h, m: min };
}

// ── CLOCKS ────────────────────────────────────────────────────────────────────────────────
// An analogue clock at the lesson's time: the hour hand short and thick (navy), the minute hand
// long and thin (amber), as the lessons describe them.
function clockFace(cx, cy, r, time, { numerals = true, rim = C.teal, face = C.white } = {}) {
  const { h, m } = parseTime(time);
  const pt = (deg, rr) => [cx + rr * Math.sin((deg * Math.PI) / 180), cy - rr * Math.cos((deg * Math.PI) / 180)];
  let s = `<circle cx="${cx}" cy="${cy}" r="${r}" fill="${face}" stroke="${rim}" stroke-width="${(r * 0.085).toFixed(1)}"/>`;
  for (let i = 0; i < 60; i++) {
    const big = i % 5 === 0;
    const [x1, y1] = pt(i * 6, r * 0.9); const [x2, y2] = pt(i * 6, r * (big ? 0.78 : 0.85));
    s += `<line x1="${x1.toFixed(1)}" y1="${y1.toFixed(1)}" x2="${x2.toFixed(1)}" y2="${y2.toFixed(1)}" stroke="${big ? C.navy : '#9AA1AE'}" stroke-width="${big ? (r * 0.03).toFixed(1) : (r * 0.012).toFixed(1)}" stroke-linecap="round"/>`;
  }
  if (numerals) {
    for (let n = 1; n <= 12; n++) {
      const [x, y] = pt(n * 30, r * 0.62);
      s += `<text x="${x.toFixed(1)}" y="${(y + r * 0.075).toFixed(1)}" text-anchor="middle" ${FONT} font-weight="700" font-size="${(r * 0.21).toFixed(1)}" fill="${C.navy}">${n}</text>`;
    }
  }
  const hourDeg = ((h % 12) + m / 60) * 30; const minDeg = m * 6;
  const [hx, hy] = pt(hourDeg, r * 0.45); const [mx, my] = pt(minDeg, r * 0.76);
  s += `<line x1="${cx}" y1="${cy}" x2="${hx.toFixed(1)}" y2="${hy.toFixed(1)}" stroke="${C.navy}" stroke-width="${(r * 0.1).toFixed(1)}" stroke-linecap="round"/>`;
  s += `<line x1="${cx}" y1="${cy}" x2="${mx.toFixed(1)}" y2="${my.toFixed(1)}" stroke="${C.amber}" stroke-width="${(r * 0.045).toFixed(1)}" stroke-linecap="round"/>`;
  s += `<circle cx="${cx}" cy="${cy}" r="${(r * 0.07).toFixed(1)}" fill="${C.navy}"/><circle cx="${cx}" cy="${cy}" r="${(r * 0.03).toFixed(1)}" fill="${C.amber}"/>`;
  return s;
}
function digitalPanel(x, y, w, h, text, { label } = {}) {
  let s = `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${h * 0.16}" fill="${C.navy}"/>`
    + `<rect x="${x + 8}" y="${y + 8}" width="${w - 16}" height="${h - 16}" rx="${h * 0.1}" fill="#1B2030"/>`
    + `<text x="${x + w / 2}" y="${y + h * 0.66}" text-anchor="middle" ${FONT} font-weight="800" font-size="${(h * 0.5).toFixed(1)}" fill="#7CF0B0" letter-spacing="2">${esc(text)}</text>`;
  if (label) {
    const parts = String(label).split('|').map((p) => p.trim());
    if (parts.length === 2) {
      s += `<line x1="${x + w / 2}" y1="${y + h + 8}" x2="${x + w / 2}" y2="${y + h + 30}" stroke="${C.slate}" stroke-width="1.5"/>`
        + `<text x="${x + w / 4}" y="${y + h + 25}" text-anchor="middle" ${FONT} font-weight="700" font-size="15" fill="${C.slate}">${esc(parts[0])}</text>`
        + `<text x="${x + (3 * w) / 4}" y="${y + h + 25}" text-anchor="middle" ${FONT} font-weight="700" font-size="15" fill="${C.slate}">${esc(parts[1])}</text>`;
    } else s += `<text x="${x + w / 2}" y="${y + h + 25}" text-anchor="middle" ${FONT} font-weight="700" font-size="15" fill="${C.slate}">${esc(label)}</text>`;
  }
  return s;
}
function clock(spec) {
  const size = 200;
  return svg(size, size, clockFace(100, 100, 92, spec.time), `clock showing ${spec.time}`);
}
function clockPair(spec) {
  const legend = spec.hour_label || spec.minute_label;
  const H = legend ? 262 : 212;
  let s = clockFace(105, 105, 96, spec.time)
    + `<text x="236" y="122" text-anchor="middle" ${FONT} font-weight="800" font-size="44" fill="${C.green}">=</text>`
    + digitalPanel(272, 58, 196, 94, spec.digital || spec.time, { label: spec.digital_label });
  if (legend) {
    const y = 236;
    if (spec.hour_label) s += `<line x1="14" y1="${y}" x2="40" y2="${y}" stroke="${C.navy}" stroke-width="9" stroke-linecap="round"/><text x="50" y="${y + 5}" ${FONT} font-weight="600" font-size="15" fill="${C.ink}">${esc(spec.hour_label)}</text>`;
    if (spec.minute_label) s += `<line x1="250" y1="${y}" x2="290" y2="${y}" stroke="${C.amber}" stroke-width="4.5" stroke-linecap="round"/><text x="300" y="${y + 5}" ${FONT} font-weight="600" font-size="15" fill="${C.ink}">${esc(spec.minute_label)}</text>`;
  }
  return svg(480, H, s, `analogue clock and digital clock both showing ${spec.digital || spec.time}`);
}

// ── LETTERS AND SOUNDS ────────────────────────────────────────────────────────────────────
function tile(x, y, w, h, text, color, fs) {
  const r1 = (v) => Math.round(v * 10) / 10;
  x = r1(x); y = r1(y); w = r1(w);
  return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${Math.min(10, h * 0.22)}" fill="${color}"/>`
    + `<rect x="${x}" y="${y + h - 6}" width="${w}" height="6" rx="3" fill="#000" opacity=".12"/>`
    + `<text x="${x + w / 2}" y="${y + h * 0.68}" text-anchor="middle" ${FONT} font-weight="800" font-size="${fs}" fill="#fff">${esc(text)}</text>`;
}
const tileW = (t, fs) => Math.max(fs * 1.5, String(t).length * fs * 0.62 + fs * 0.9);
// a row of tiles; returns {s, w}
function tileRow(parts, x, y, h, fs, gap = 8) {
  let s = ''; let cx = x;
  parts.forEach((p, i) => { const w = tileW(p, fs); s += tile(cx, y, w, h, p, TILE[i % TILE.length], fs); cx += w + gap; });
  return { s, w: cx - gap - x };
}
function tiles(spec) {
  const { s, w } = tileRow(spec.parts, 4, 4, 46, 24);
  return svg(Math.ceil(w + 8), 56, s, `letter tiles ${spec.parts.join(' ')}`);
}
// the word blender: the sounds drop into a blender and come out as one word
function blender(spec) {
  const { parts, word } = spec;
  let s = '';
  const fs = 22; const ws = parts.map((p) => tileW(p, fs)); const total = ws.reduce((a, b) => a + b, 0) + 8 * (parts.length - 1);
  let x = 128 - total / 2;
  parts.forEach((p, i) => { s += tile(x, 6 + (i % 2) * 10, ws[i], 40, p, TILE[i % TILE.length], fs); x += ws[i] + 8; });
  // the blender jar, lid and base
  s += '<path d="M78 74h100l-12 92H90z" fill="#CFEFFF" stroke="#2E86DE" stroke-width="4" stroke-linejoin="round"/>'
    + '<path d="M90 120h76M92 140h72" stroke="#2E86DE" stroke-width="2" opacity=".35"/>'
    + '<rect x="72" y="64" width="112" height="14" rx="6" fill="#2E86DE"/>'
    + '<path d="M86 166h84l8 30H78z" fill="#2E5E90"/><circle cx="128" cy="182" r="7" fill="#F2A20C"/>'
    + '<path d="M128 132l-14 6m14-6l14 6" stroke="#2E86DE" stroke-width="3" stroke-linecap="round"/>';
  // arrow out to the word
  s += `<path d="M196 122h70" stroke="${C.green}" stroke-width="6" stroke-linecap="round"/><path d="M258 106l20 16-20 16z" fill="${C.green}"/>`;
  const wfs = 34; const ww = Math.max(140, String(word).length * wfs * 0.62 + 40);
  s += `<rect x="292" y="94" width="${ww}" height="58" rx="29" fill="${C.green}"/><text x="${292 + ww / 2}" y="134" text-anchor="middle" ${FONT} font-weight="800" font-size="${wfs}" fill="#fff">${esc(word)}</text>`;
  return svg(Math.max(480, 300 + ww), 204, s, `word blender: ${parts.join(' + ')} makes ${word}`);
}
// the board's word blender: each word's sounds as tiles, an arrow, and a line to write the word on
function blenderList(spec) {
  const rows = spec.words; const h = 40; const gap = 12; const fs = 20;
  let s = '';
  rows.forEach((parts, r) => {
    const y = r * (h + gap) + 4;
    const { s: t, w } = tileRow(parts, 4, y, h, fs, 6);
    s += t;
    const ax = Math.max(220, w + 20);
    s += `<path d="M${ax} ${y + h / 2}h34" stroke="${C.slate}" stroke-width="4" stroke-linecap="round"/><path d="M${ax + 32} ${y + h / 2 - 8}l12 8-12 8z" fill="${C.slate}"/>`
      + `<line x1="${ax + 58}" y1="${y + h - 6}" x2="${ax + 210}" y2="${y + h - 6}" stroke="${C.navy}" stroke-width="3" stroke-dasharray="2 7" stroke-linecap="round"/>`;
  });
  return svg(480, rows.length * (h + gap) + 4, s, `word blender: ${rows.map((p) => p.join('-')).join(', ')}`);
}
// blending step by step: s + u = su, su + nn = sun, sun + y = sunny
// The steps are the lesson's own ("'su' + 'nn' = 'sun'": a double letter is one sound), so they
// come from the lesson, never from joining the letters.
function blendSteps(spec) {
  const steps = spec.steps;
  const h = 40; const gap = 12; const fs = 20; let s = '';
  steps.forEach(([a, b, out], r) => {
    const y = r * (h + gap) + 4; const x0 = 4 + r * 26;
    const wa = tileW(a, fs); const wb = tileW(b, fs);
    s += tile(x0, y, wa, h, a, r === 0 ? TILE[0] : '#7F8A9C', fs);
    s += `<text x="${x0 + wa + 14}" y="${y + 28}" text-anchor="middle" ${FONT} font-weight="800" font-size="24" fill="${C.slate}">+</text>`;
    s += tile(x0 + wa + 28, y, wb, h, b, TILE[(r + 1) % TILE.length], fs);
    const ex = x0 + wa + wb + 44;
    s += `<text x="${ex + 8}" y="${y + 28}" text-anchor="middle" ${FONT} font-weight="800" font-size="24" fill="${C.slate}">=</text>`;
    const last = r === steps.length - 1; const wo = tileW(out, fs) + (last ? 12 : 0);
    s += `<rect x="${ex + 24}" y="${y}" width="${wo}" height="${h}" rx="9" fill="${last ? C.green : '#fff'}" stroke="${last ? C.green : C.slate}" stroke-width="2.5"/>`
      + `<text x="${ex + 24 + wo / 2}" y="${y + 28}" text-anchor="middle" ${FONT} font-weight="800" font-size="${fs}" fill="${last ? '#fff' : C.ink}">${esc(out)}</text>`;
  });
  return svg(480, steps.length * (h + gap) + 4, s, `blending step by step: ${steps.map((st) => `${st[0]} + ${st[1]} = ${st[2]}`).join(', ')}`);
}

// ── SCENES ────────────────────────────────────────────────────────────────────────────────
const sunAt = (x, y, r) => `<circle cx="${x}" cy="${y}" r="${r}" fill="${C.sun}"/>${[0, 45, 90, 135, 180, 225, 270, 315].map((d) => {
  const a = (d * Math.PI) / 180; return `<line x1="${(x + Math.cos(a) * r * 1.3).toFixed(1)}" y1="${(y + Math.sin(a) * r * 1.3).toFixed(1)}" x2="${(x + Math.cos(a) * r * 1.7).toFixed(1)}" y2="${(y + Math.sin(a) * r * 1.7).toFixed(1)}" stroke="${C.sun}" stroke-width="4" stroke-linecap="round"/>`;
}).join('')}`;
const cloud = (x, y, k = 1) => `<g transform="translate(${x} ${y}) scale(${k})" fill="#fff"><ellipse cx="0" cy="0" rx="26" ry="14"/><ellipse cx="22" cy="-8" rx="20" ry="16"/><ellipse cx="44" cy="0" rx="22" ry="13"/></g>`;
// a child, flat style; o = {skin, top, scarf, hair, look:'up'|'ahead'}
function child(x, y, o = {}) {
  const skin = o.skin || '#D9A07A'; const top = o.top || '#7E57C2';
  const up = o.look === 'up';
  return `<g transform="translate(${x} ${y})">`
    + `<path d="M-16 40h32l4 50h-14l-6-34-6 34h-14z" fill="${o.legs || '#3D4A66'}"/>`
    + `<path d="M-22 4c2-8 10-12 22-12s20 4 22 12l4 40h-52z" fill="${top}"/>`
    + `<rect x="-6" y="-18" width="12" height="12" rx="4" fill="${skin}"/>`
    // a headscarf frames the face: drawn behind the head, with a band over the forehead
    + (o.scarf ? `<path d="M-21 -30c0-17 9-26 21-26s21 9 21 26c0 10-3 22-9 30h-24c-6-8-9-20-9-30z" fill="${o.scarf}"/>` : '')
    + `<ellipse cx="0" cy="${up ? -32 : -30}" rx="${o.scarf ? 13 : 16}" ry="${o.scarf ? 15 : 17}" fill="${skin}"/>`
    + (o.scarf ? `<path d="M-14 -38c2-8 8-12 14-12s12 4 14 12c-4-3-9-4-14-4s-10 1-14 4z" fill="${o.scarf}" stroke="#D96A93" stroke-width="1"/>`
      : `<path d="M-16 -34c0-12 7-18 16-18s16 6 16 18c-4-6-9-8-16-8s-12 2-16 8z" fill="${o.hair || '#2B2521'}"/>`)
    + `<circle cx="-6" cy="${up ? -37 : -31}" r="2" fill="#2B2521"/><circle cx="6" cy="${up ? -37 : -31}" r="2" fill="#2B2521"/>`
    + (o.glasses ? `<g fill="none" stroke="#2B2521" stroke-width="1.8"><circle cx="-6" cy="${up ? -37 : -31}" r="5"/><circle cx="6" cy="${up ? -37 : -31}" r="5"/><path d="M-1 ${up ? -37 : -31}h2"/></g>` : '')
    + (o.mouth === 'o' ? `<ellipse cx="0" cy="${up ? -26 : -22}" rx="3" ry="4" fill="#7A2E2E"/>` : `<path d="M-5 ${up ? -27 : -23}c3 3 7 3 10 0" stroke="#7A2E2E" stroke-width="2" fill="none" stroke-linecap="round"/>`)
    + '</g>';
}
function bird(x, y, k = 1) {
  return `<g transform="translate(${x} ${y}) scale(${k})">`
    + '<ellipse cx="0" cy="0" rx="20" ry="14" fill="#FFD43B"/><circle cx="16" cy="-10" r="10" fill="#FFD43B"/>'
    + '<path d="M-8 -2c-6 8-16 8-22 4 8-2 14-6 18-12z" fill="#F2A20C"/>'
    + '<path d="M25 -12l10-2-10 6z" fill="#F08C00"/><path d="M25 -9l9 3-9 0z" fill="#E8590C"/>'
    + '<circle cx="18" cy="-12" r="2.2" fill="#2B2521"/><path d="M-2 13v6M6 13v6" stroke="#8A5A3B" stroke-width="2.5" stroke-linecap="round"/>'
    + '</g>';
}
const note = (x, y, c = C.purple) => `<g transform="translate(${x} ${y})" fill="${c}"><ellipse cx="0" cy="12" rx="6" ry="4.5" transform="rotate(-20 0 12)"/><rect x="4.5" y="-10" width="2.6" height="22"/><path d="M7 -10c6 2 9 6 8 12-2-4-5-6-8-6z"/></g>`;
function tree(x, y, k = 1) {
  return `<g transform="translate(${x} ${y}) scale(${k})"><path d="M-10 0h20l-4 -80h-12z" fill="${C.trunk}"/>`
    + `<circle cx="0" cy="-100" r="46" fill="${C.leaf}"/><circle cx="-34" cy="-78" r="30" fill="#5DB868"/><circle cx="34" cy="-80" r="32" fill="#469A52"/></g>`;
}
function pine(x, y, k = 1, c = '#2F7D4A') {
  return `<g transform="translate(${x} ${y}) scale(${k})"><rect x="-4" y="-12" width="8" height="14" fill="${C.trunk}"/>`
    + `<path d="M0 -70l22 34h-10l16 24h-56l16-24h-10z" fill="${c}"/></g>`;
}
const SCENES = {
  songbird: () => {
    let s = '<defs><linearGradient id="qsky1" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#BFE3FA"/><stop offset="1" stop-color="#EAF6FD"/></linearGradient></defs>'
      + '<rect width="480" height="230" rx="14" fill="url(#qsky1)"/>' + sunAt(420, 44, 20) + cloud(250, 40, 0.9)
      + '<path d="M0 190c80-14 160-14 240-6s160 10 240-4v50H0z" fill="#9AD27B"/><path d="M0 206c90-8 200-6 300 0s130 2 180-4v32H0z" fill="#7CBF5E"/>';
    // the tree on the left with a long branch reaching right; the songbird on the branch, singing
    s += '<path d="M64 200h26l-4-120h-18z" fill="#8A5A3B"/><path d="M80 112c40-6 90-6 140 6" stroke="#8A5A3B" stroke-width="9" stroke-linecap="round" fill="none"/>'
      + '<circle cx="74" cy="70" r="50" fill="#4FA35B"/><circle cx="40" cy="92" r="30" fill="#5DB868"/><circle cx="112" cy="84" r="32" fill="#469A52"/>'
      + '<ellipse cx="206" cy="112" rx="14" ry="6" fill="#5DB868"/>'
      + bird(184, 92, 1.05) + note(222, 56) + note(246, 36, C.blue) + note(262, 70, C.red);
    // Pinky, pink headscarf and purple top, looking up in surprise
    s += child(330, 168, { scarf: C.pink, top: '#8E5BC6', look: 'up', mouth: 'o' }) + child(392, 178, { top: '#F28C28', hair: '#3B2A20', look: 'up', glasses: true });
    return svg(480, 230, s, 'Pinky looks up at a yellow songbird singing on a tree branch');
  },
  kite_tree: () => {
    let s = '<rect width="480" height="230" rx="14" fill="#D7EEFB"/>' + cloud(60, 44, 0.8) + cloud(330, 30, 0.7)
      + '<path d="M0 196c120-12 240-12 480 0v34H0z" fill="#8CCB6E"/>';
    s += tree(180, 200, 1.25);
    // the kite stuck high in the tree, its string hanging down
    s += '<g transform="translate(206 62) rotate(18)"><path d="M0 -30l22 30-22 34-22-34z" fill="#E5534B"/><path d="M0 -30v64M-22 0h44" stroke="#FFD43B" stroke-width="3"/></g>'
      + '<path d="M212 98c10 30-6 50 6 76" stroke="#3D4A66" stroke-width="2" fill="none" stroke-dasharray="1 0"/>'
      + '<path d="M216 120l8-4m-6 22l8 2m-4 18l8-4" stroke="#E5534B" stroke-width="3" stroke-linecap="round"/>';
    // a boy looking up at it
    s += child(330, 170, { top: '#2E86DE', look: 'up', mouth: 'o' });
    s += '<path d="M352 128l26-26" stroke="#D9A07A" stroke-width="7" stroke-linecap="round"/>';
    return svg(480, 230, s, 'a boy looks up at a kite stuck high in a tree');
  },
  lake: () => {
    let s = '<defs><linearGradient id="qsky2" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#A9D8F5"/><stop offset="1" stop-color="#E6F4FC"/></linearGradient>'
      + '<linearGradient id="qlake" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#3FA7C9"/><stop offset="1" stop-color="#1F7FA6"/></linearGradient></defs>'
      + '<rect width="480" height="230" rx="14" fill="url(#qsky2)"/>' + cloud(70, 40, 0.8) + cloud(360, 34, 0.7);
    // snowy mountains behind the lake
    s += '<path d="M-10 150l90-96 60 54 70-80 90 100 50-44 80 66v20H-10z" fill="#7C8FA6"/>'
      + '<path d="M80 54l-24 26 14-4 10 10 12-14 10 6z" fill="#fff"/><path d="M210 28l-26 30 14-4 12 12 12-12 14 8z" fill="#fff"/><path d="M350 84l-18 18 10-2 8 8 8-8 10 4z" fill="#fff"/>'
      + '<path d="M-10 160l120-50 80 40 90-46 110 56 100-30v40H-10z" fill="#5E7A93"/>';
    // the lake with light on the water, green banks, pine trees
    s += '<ellipse cx="240" cy="182" rx="230" ry="34" fill="url(#qlake)"/>'
      + '<path d="M130 178h60M260 186h80M200 196h50M330 172h40" stroke="#fff" stroke-width="3" stroke-linecap="round" opacity=".55"/>'
      + '<path d="M0 200c40-10 70-8 100 4s-60 26-100 26z" fill="#6DBA62"/><path d="M480 196c-50-10-90-6-120 6s70 28 120 28z" fill="#6DBA62"/>'
      + pine(30, 206, 1) + pine(62, 214, 0.8, '#3B8F57') + pine(420, 208, 1) + pine(452, 214, 0.85, '#3B8F57')
      + '<path d="M300 176l30 0-6 7h-20z" fill="#B9733C"/><path d="M315 176v-18l12 14z" fill="#fff"/>';
    return svg(480, 230, s, 'a lake with snowy mountains and pine trees');
  },
};
function scene(spec) {
  const f = SCENES[spec.scene];
  if (!f) throw new Error(`scene: no drawing for "${spec.scene}"`);
  return f();
}

// ── BOOKS ─────────────────────────────────────────────────────────────────────────────────
// wrap text for SVG at about n characters a line
function wrap(text, n) {
  const out = []; let line = '';
  for (const w of String(text).split(/\s+/)) {
    if ((line + ' ' + w).trim().length > n && line) { out.push(line); line = w; } else line = (line + ' ' + w).trim();
  }
  if (line) out.push(line);
  return out;
}
// the board's prediction: the book's title and picture, and a thought bubble for the guess
function predict(spec) {
  let s = '<rect x="10" y="12" width="190" height="210" rx="12" fill="#2E5E90"/><rect x="10" y="12" width="18" height="210" rx="6" fill="#244B75"/>'
    + '<rect x="40" y="70" width="146" height="110" rx="8" fill="#D7EEFB"/>'
    + '<path d="M40 160c40-8 100-8 146 0v20H40z" fill="#8CCB6E"/><path d="M70 172h10l-2-50h-6z" fill="#8A5A3B"/><circle cx="75" cy="112" r="24" fill="#4FA35B"/>'
    + '<path d="M78 128c26-2 50 0 70 4" stroke="#8A5A3B" stroke-width="5" stroke-linecap="round"/>' + bird(140, 116, 0.6);
  wrap(spec.title, 16).slice(0, 2).forEach((l, i) => { s += `<text x="113" y="${40 + i * 22}" text-anchor="middle" ${FONT} font-weight="800" font-size="18" fill="#fff">${esc(l)}</text>`; });
  // thought bubble
  s += '<circle cx="216" cy="190" r="6" fill="#fff" stroke="#584A93" stroke-width="2.5"/><circle cx="234" cy="170" r="10" fill="#fff" stroke="#584A93" stroke-width="2.5"/>'
    + '<path d="M262 150c-30 0-36-40-10-48 0-30 40-40 60-20 16-24 64-20 72 6 30-2 44 34 22 50 14 26-14 50-40 40-14 22-60 22-72 0-20 8-36-6-32-28z" fill="#fff" stroke="#584A93" stroke-width="3"/>';
  // the prompt, each word on its own line where it is long, inside the bubble
  const pr = wrap(String(spec.prompt).replace(/_{3,}/g, '______'), 11);
  pr.forEach((l, i) => { s += `<text x="352" y="${130 + i * 24 - (pr.length - 1) * 12}" text-anchor="middle" ${FONT} font-weight="800" font-size="17" fill="#584A93">${esc(l)}</text>`; });
  return svg(480, 232, s, `book cover "${spec.title}" and a thought bubble: ${spec.prompt}`);
}
// a picture dictionary open at the word's letter, with the word's entry
function dictionary(spec) {
  const letter = String(spec.word || '?').charAt(0).toUpperCase();
  let s = '<path d="M240 30c-50-18-130-18-220 0v176c90-18 170-18 220 0z" fill="#FFF8E8" stroke="#C9A35A" stroke-width="3"/>'
    + '<path d="M240 30c50-18 130-18 220 0v176c-90-18-170-18-220 0z" fill="#FFFDF6" stroke="#C9A35A" stroke-width="3"/>'
    + '<path d="M240 30v176" stroke="#C9A35A" stroke-width="3"/>'
    + `<rect x="436" y="40" width="34" height="40" rx="6" fill="${C.amber}"/><text x="453" y="69" text-anchor="middle" ${FONT} font-weight="800" font-size="22" fill="#fff">${esc(letter)}</text>`
    + `<text x="128" y="96" text-anchor="middle" ${FONT} font-weight="800" font-size="76" fill="${C.amber}">${esc(letter)}</text>`
    + `<text x="128" y="132" text-anchor="middle" ${FONT} font-weight="700" font-size="20" fill="${C.slate}">${esc(letter.toLowerCase())}a  ${esc(letter.toLowerCase())}e  ${esc(letter.toLowerCase())}u …</text>`
    + `<rect x="262" y="60" width="160" height="32" rx="8" fill="${C.mint}"/><text x="272" y="83" ${FONT} font-weight="800" font-size="20" fill="${C.green}">${esc(spec.word)}</text>`;
  const rest = String(spec.entry || '').replace(new RegExp(`^${String(spec.word).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*,?\\s*`), '');
  wrap(rest, 20).slice(0, 4).forEach((l, i) => { s += `<text x="266" y="${120 + i * 24}" ${FONT} font-weight="500" font-size="17" fill="${C.ink}">${esc(l)}</text>`; });
  return svg(480, 220, s, `dictionary entry: ${spec.entry}`);
}

// ── THE HERO BADGE ───────────────────────────────────────────────────────────────────────
// A small round picture for the lesson's title card.
function heroBadge(spec) {
  if (!spec) return '';
  if (spec.type === 'clock') return `<svg class="qhero-art" viewBox="0 0 120 120" aria-hidden="true">${clockFace(60, 60, 54, spec.time, { rim: C.amber })}</svg>`;
  if (spec.type === 'scene') {
    const inner = scene(spec).replace(/^<svg[^>]*>/, '').replace(/<\/svg>$/, '');
    const box = { songbird: '150 20 190 190', lake: '90 20 260 210', kite_tree: '120 20 230 210' }[spec.scene] || '0 0 480 230';
    return `<svg class="qhero-art" viewBox="${box}" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><defs><clipPath id="qhc"><rect x="-1000" y="-1000" width="3000" height="3000"/></clipPath></defs>${inner}</svg>`;
  }
  return '';
}

// ── ICONS for labels ──────────────────────────────────────────────────────────────────────
const ICON = {
  key: (c = C.amber) => `<svg class="qic" viewBox="0 0 24 24" aria-hidden="true"><circle cx="8" cy="9" r="5" fill="none" stroke="${c}" stroke-width="2.6"/><path d="M11.5 12.5 20 21M16 17l2.5-2.5M18.5 19.5 21 17" stroke="${c}" stroke-width="2.6" stroke-linecap="round"/></svg>`,
  tv: (c = '#8A5A00') => `<svg class="qic" viewBox="0 0 24 24" aria-hidden="true"><rect x="2" y="5" width="20" height="14" rx="3" fill="${c}"/><rect x="4.5" y="7.5" width="15" height="9" rx="1.5" fill="#FFF8E8"/><path d="M10 10.2v4.6l4-2.3z" fill="${c}"/><path d="M8 22h8" stroke="${c}" stroke-width="2" stroke-linecap="round"/></svg>`,
  clock: (c = C.slate) => `<svg class="qic" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9.5" fill="none" stroke="${c}" stroke-width="2.2"/><path d="M12 6.5V12l3.8 2.3" stroke="${c}" stroke-width="2.2" stroke-linecap="round" fill="none"/></svg>`,
  mic: (c = '#fff') => `<svg class="qic" viewBox="0 0 24 24" aria-hidden="true"><rect x="8.5" y="2" width="7" height="12.5" rx="3.5" fill="${c}"/><path fill="none" stroke="${c}" stroke-width="2" stroke-linecap="round" d="M5.5 11a6.5 6.5 0 0 0 13 0M12 17.5V21M8.5 21.5h7"/></svg>`,
  chat: (c = '#fff') => `<svg class="qic" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="${c}" stroke-width="2" d="M12 2.8a9.2 9.2 0 0 0-8 13.7L2.8 21.2l4.8-1.2A9.2 9.2 0 1 0 12 2.8z"/><path fill="${c}" d="M8.6 7.4c.3-.3.8-.3 1 .1l1 1.9c.2.3.1.7-.2 1l-.6.6c.6 1.3 1.6 2.3 2.9 2.9l.6-.6c.3-.3.7-.4 1-.2l1.9 1c.4.2.4.7.1 1l-.9 1c-.6.6-1.6.7-2.4.3-2.2-1.1-3.9-2.8-5-5-.4-.8-.3-1.8.3-2.4l.8-.8z"/></svg>`,
  reply: (c = '#fff') => `<svg class="qic" viewBox="0 0 24 24" aria-hidden="true"><path fill="${c}" d="M10 5 3 11.5l7 6.5v-4c5 0 8.5 1.5 11 5-1-5.5-4.5-10-11-11V5z"/></svg>`,
  house: (c = C.slate) => `<svg class="qic" viewBox="0 0 24 24" aria-hidden="true"><path fill="${c}" d="M12 3 1.5 12h3v9h5.5v-6h4v6h5.5v-9h3L12 3z"/></svg>`,
  bubble: (c = C.blue) => `<svg class="qic" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="${c}" stroke-width="2.2" stroke-linejoin="round" d="M4 4h16a1.5 1.5 0 0 1 1.5 1.5v10A1.5 1.5 0 0 1 20 17h-9l-5 4v-4H4a1.5 1.5 0 0 1-1.5-1.5v-10A1.5 1.5 0 0 1 4 4z"/><path d="M7 9h10M7 12.5h6" stroke="${c}" stroke-width="2" stroke-linecap="round"/></svg>`,
  star: (c = C.amber) => `<svg class="qic" viewBox="0 0 24 24" aria-hidden="true"><path fill="${c}" d="M12 2.5l2.9 6 6.6.9-4.8 4.6 1.2 6.5L12 17.4l-5.9 3.1 1.2-6.5L2.5 9.4l6.6-.9z"/></svg>`,
  help: (c = C.blue) => `<svg class="qic" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="10" fill="${c}"/><path d="M9.2 9.2a2.9 2.9 0 1 1 4.2 2.6c-.9.5-1.4 1.1-1.4 2.1v.6" stroke="#fff" stroke-width="2.3" fill="none" stroke-linecap="round"/><circle cx="12" cy="17.6" r="1.4" fill="#fff"/></svg>`,
};
// a face for a speaker in the read-aloud lines, one colour per speaker
const FACE_TOPS = ['#8E5BC6', '#2E86DE', '#F28C28', '#16A085', '#E5534B'];
function face(i) {
  const top = FACE_TOPS[i % FACE_TOPS.length];
  return `<svg class="qface" viewBox="0 0 40 40" aria-hidden="true"><circle cx="20" cy="20" r="20" fill="${top}" opacity=".18"/>`
    + `<path d="M7 40c1-9 6-13 13-13s12 4 13 13z" fill="${top}"/><circle cx="20" cy="17" r="9" fill="#D9A07A"/>`
    + `<path d="M11 15c0-6 4-9 9-9s9 3 9 9c-2-3-5-4-9-4s-7 1-9 4z" fill="#2B2521"/>`
    + '<circle cx="17" cy="17" r="1.2" fill="#2B2521"/><circle cx="23" cy="17" r="1.2" fill="#2B2521"/><path d="M17 21c2 1.5 4 1.5 6 0" stroke="#7A2E2E" stroke-width="1.3" fill="none" stroke-linecap="round"/></svg>';
}

const DRAW = { clock, clock_pair: clockPair, tiles, blender, blender_list: blenderList, blend_steps: blendSteps, scene, predict, dictionary };
// the visual types drawn as HTML by primary.js rather than as SVG here
const HTML_VISUALS = ['story_map', 'tracker'];
function draw(spec) {
  if (!spec || !spec.type) return '';
  const f = DRAW[spec.type];
  if (!f) throw new Error(`no drawing for visual type "${spec.type}"`);
  return f(spec);
}

module.exports = { draw, DRAW, HTML_VISUALS, heroBadge, ICON, face, parseTime, C };
