#!/usr/bin/env node
'use strict';
// Generate a lesson-plan PDF from a lesson JSON file, using the lp-render module.
//
// Usage:
//   node scripts/render-lesson.js <lesson.json> [--locale=en|ur|sd|ar] [--a4] [--images [--source=wikimedia|flickr]] [--out=path.pdf]
//
// Examples:
//   node scripts/render-lesson.js lp-render/fixtures/lesson-113087.en.json
//   node scripts/render-lesson.js my-lesson.json --locale=ur --out=out/urdu.pdf
//   node scripts/render-lesson.js my-lesson.json --a4        # fixed A4 pages (default is content-fit, no blank space)
//   node scripts/render-lesson.js my-lesson.json --images    # resolve picture_cards via dataset icons + Openverse photos first
//   node scripts/render-lesson.js my-lesson.json --auto-images --source=flickr   # AUTO-detect photo-worthy concepts, then fetch
//   KIE_API_KEY=... node scripts/render-lesson.js my-lesson.json --gen-images   # AI-GENERATE picture_cards kind:"gen" via kie.ai
//
// --gen-images runs the imagegen bridge: any picture_cards card with kind:"gen" is generated by
// kie.ai (decorative_scene / labeled_diagram model ladder + VLM quality gate) and embedded as a
// base64 image. Needs KIE_API_KEY. Cards that fail the gate fall back to blank/deterministic.
// --images runs the resolveImages pre-step so picture_cards `{query, kind}` hints become inline
// SVG icons (library) or real Creative-Commons photos (Openverse).
// --auto-images additionally SCANS the lesson content first and auto-adds a picture_cards
// section for the concrete real-world concepts it finds (animals, fruits, places, …) — no manual
// hints needed. It implies --images. Default source is `wikimedia` (production); pass
// --source=flickr for local/sandbox where Wikimedia Commons is unreachable.
const fs = require('node:fs');
const path = require('node:path');
const { renderLessonPlanPdf, resolveImages, autoImages, validateLesson, closeBrowser } = require('../lp-render');
const { resolveGenCards } = require('../imagegen/lp-bridge');

function parseArgs(argv) {
  const args = { _: [] };
  for (const a of argv) {
    if (a === '--a4') args.a4 = true;
    else if (a === '--images') args.images = true;
    else if (a === '--gen-images') args.genImages = true;
    else if (a === '--auto-images') { args.autoImages = true; args.images = true; }
    else if (a.startsWith('--locale=')) args.locale = a.slice('--locale='.length);
    else if (a.startsWith('--source=')) args.source = a.slice('--source='.length);
    else if (a.startsWith('--out=')) args.out = a.slice('--out='.length);
    else args._.push(a);
  }
  return args;
}

(async () => {
  const args = parseArgs(process.argv.slice(2));
  const input = args._[0];
  if (!input) {
    console.error('Usage: node scripts/render-lesson.js <lesson.json> [--locale=en|ur|sd|ar] [--a4] [--images [--source=wikimedia|flickr]] [--out=path.pdf]');
    process.exit(2);
  }
  if (!fs.existsSync(input)) { console.error(`No such file: ${input}`); process.exit(2); }

  let lesson;
  try { lesson = JSON.parse(fs.readFileSync(input, 'utf8')); }
  catch (e) { console.error(`Invalid JSON in ${input}: ${e.message}`); process.exit(1); }

  const { ok, errors } = validateLesson(lesson);
  if (!ok) { console.error('Invalid lesson:\n - ' + errors.join('\n - ')); process.exit(1); }

  const locale = args.locale || (lesson.meta && lesson.meta.locale) || 'en';
  const opts = { locale };
  if (args.a4) opts.pageMode = 'a4';

  // Optional pre-steps: AI-generate gen cards, auto-detect concepts, resolve image hints.
  let lessonToRender = lesson;
  if (args.genImages) {
    const apiKey = process.env.KIE_API_KEY;
    if (!apiKey) { console.error('--gen-images needs KIE_API_KEY in the environment'); process.exit(1); }
    const { lesson: withGen, report } = await resolveGenCards(lessonToRender, { apiKey });
    lessonToRender = withGen;
    const done = report.filter((r) => r.gate).map((r) => `${r.blockType}:${r.model}`);
    console.log(`AI-generated ${done.length} image(s) via kie.ai: ${done.join(', ') || '(none passed the gate)'}`);
  }
  if (args.autoImages) {
    const { lesson: withCards, cards } = await autoImages(lesson);
    lessonToRender = withCards;
    console.log(`Auto-detected ${cards.length} photo concept(s): ${cards.map((c) => c.query).join(', ') || '(none)'}`);
  }
  if (args.images) {
    const source = args.source || 'wikimedia';
    const { lesson: enriched, report } = await resolveImages(lessonToRender, { source });
    lessonToRender = enriched;
    const tally = report.reduce((m, r) => { m[r.used] = (m[r.used] || 0) + 1; return m; }, {});
    console.log(`Resolved images (source=${source}): ${report.length} card(s) → ${JSON.stringify(tally)}`);
  }

  const pdf = await renderLessonPlanPdf(lessonToRender, opts);
  const out = args.out || input.replace(/\.json$/i, '') + `.${locale}.pdf`;
  fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });
  fs.writeFileSync(out, pdf);
  await closeBrowser();
  console.log(`Wrote ${out} — ${pdf.length} bytes · locale=${locale} · pageMode=${opts.pageMode || 'fit'}`);
})().catch((e) => { console.error(e.message); process.exit(1); });
